/**
 * Builds supabase/seed.sql from data/league-2026-27.json. Pure and offline: same input, same
 * bytes out. Rows are keyed by natural keys (codes, slugs, names) and resolved with joins, so the
 * SQL needs no generated ids and every insert is safe to re-run.
 *
 *   pnpm db:seed:build
 */
import { readFileSync, writeFileSync } from "node:fs";
import { SPORTS, SPORT_CODES } from "../src/domain/sports/sports";
import { leagueSchema, type League } from "./league-schema";

const DATA_PATH = new URL("../data/league-2026-27.json", import.meta.url);
const OUT_PATH = new URL("../supabase/seed.sql", import.meta.url);

const str = (v: string | null) => (v === null ? "null" : `'${v.replaceAll("'", "''")}'`);
const num = (v: number | null | undefined) => (v === null || v === undefined ? "null" : String(v));
const bool = (v: boolean) => (v ? "true" : "false");
const values = (rows: string[][]) => rows.map((r) => `  (${r.join(", ")})`).join(",\n");

/** Fails the build (and so the commit) when the roster breaks a league rule. */
function assertRosterIsValid(league: League) {
  const fail = (message: string): never => {
    throw new Error(`Invalid league data: ${message}`);
  };
  if (league.teams.length !== 20) fail(`expected 20 teams, found ${league.teams.length}`);
  if (league.sports.length !== SPORT_CODES.length) fail("every sport needs an entry");
  if (new Set(league.teams.map((t) => t.slug)).size !== league.teams.length) fail("duplicate slug");
  if (new Set(league.teams.map((t) => t.name)).size !== league.teams.length) fail("duplicate name");

  for (const sport of league.sports) {
    const known = new Set(sport.participants.map((p) => p.name));
    if (known.size !== sport.participants.length) fail(`${sport.code}: duplicate participant`);
    if (sport.allows_duplicate_picks !== (sport.code === "wnba"))
      fail(`${sport.code}: only wnba allows duplicate picks`);

    const picked = league.teams.map((t) => t.picks[sport.code]);
    if (picked.some((name) => name === undefined)) fail(`${sport.code}: a team has no pick`);
    for (const name of picked)
      if (!known.has(name ?? "")) fail(`${sport.code}: unknown pick ${name}`);
    if (!sport.allows_duplicate_picks && new Set(picked).size !== picked.length)
      fail(`${sport.code}: duplicate picks across teams`);
    if (SPORTS[sport.code].participantKind === "athlete" && sport.season.major_points_cap === null)
      fail(`${sport.code}: athlete sports need major_points_cap`);

    for (const rule of sport.rules) {
      const isBand = rule.kind === "final_rank_band";
      if (isBand !== (rule.rank_from !== undefined && rule.rank_to !== undefined))
        fail(`${sport.code}/${rule.code}: rank range only on final_rank_band`);
      if (rule.is_championship && rule.code !== "champion")
        fail(`${sport.code}/${rule.code}: only champion rules are championships`);
    }
    if (new Set(sport.rules.map((r) => r.code)).size !== sport.rules.length)
      fail(`${sport.code}: duplicate rule code`);
  }
  for (const team of league.teams)
    if (Object.keys(team.picks).length !== SPORT_CODES.length) fail(`${team.name}: needs 11 picks`);
}

function build(league: League): string {
  const s = league.season;
  const out: string[] = [
    "-- GENERATED by scripts/build-seed.ts from data/league-2026-27.json. Do not edit by hand.",
    "",
    `insert into public.seasons (name, starts_on, ends_on, playoff_scoring_mode, is_active) values`,
    values([
      [
        str(s.name),
        str(s.starts_on),
        str(s.ends_on),
        str(s.playoff_scoring_mode),
        bool(s.is_active),
      ],
    ]),
    "on conflict do nothing;",
    "",
  ];

  const sportRows = league.sports.map((sp) => {
    const def = SPORTS[sp.code];
    return [
      str(sp.code),
      str(def.name),
      str(def.participantKind),
      str(def.espnSport),
      str(def.espnLeague),
      bool(sp.allows_duplicate_picks),
      String(SPORT_CODES.indexOf(sp.code) * 10),
    ];
  });
  out.push(
    "insert into public.sports (code, name, participant_kind, espn_sport, espn_league, allows_duplicate_picks, sort_order) values",
    values(sportRows),
    "on conflict do nothing;",
    "",
  );

  const seasonSportRows = league.sports.map((sp) => [
    str(sp.code),
    str(sp.season.starts_on),
    String(sp.season.espn_season),
    num(sp.season.major_points_cap),
  ]);
  out.push(
    "insert into public.season_sports (season_id, sport_id, starts_on, espn_season, major_points_cap)",
    "select se.id, sp.id, v.starts_on::date, v.espn_season, v.cap::numeric",
    "from (values",
    values(seasonSportRows),
    ") as v(code, starts_on, espn_season, cap)",
    "join public.sports sp on sp.code = v.code",
    `join public.seasons se on se.name = ${str(s.name)}`,
    "on conflict do nothing;",
    "",
  );

  const ruleRows = league.sports.flatMap((sp) =>
    sp.rules.map((r, i) => [
      str(sp.code),
      str(r.code),
      str(r.label),
      str(r.kind),
      String(r.points),
      num(r.rank_from),
      num(r.rank_to),
      bool(r.is_championship),
      String((i + 1) * 10),
    ]),
  );
  out.push(
    "insert into public.scoring_rules (season_id, sport_id, code, label, kind, points, rank_from, rank_to, is_championship, sort_order)",
    "select se.id, sp.id, v.rule_code, v.label, v.kind::public.scoring_rule_kind, v.points::numeric,",
    "  v.rank_from::integer, v.rank_to::integer, v.is_championship::boolean, v.sort_order::integer",
    "from (values",
    values(ruleRows),
    ") as v(sport_code, rule_code, label, kind, points, rank_from, rank_to, is_championship, sort_order)",
    "join public.sports sp on sp.code = v.sport_code",
    `join public.seasons se on se.name = ${str(s.name)}`,
    "on conflict do nothing;",
    "",
  );

  const participantRows = league.sports.flatMap((sp) =>
    sp.participants.map((p) => [
      str(sp.code),
      str(p.name),
      str(p.short_name),
      str(p.espn_id),
      str(p.logo_url),
      str(p.primary_color),
    ]),
  );
  out.push(
    "insert into public.participants (sport_id, name, short_name, espn_id, logo_url, primary_color)",
    "select sp.id, v.name, v.short_name, v.espn_id, v.logo_url, v.primary_color",
    "from (values",
    values(participantRows),
    ") as v(sport_code, name, short_name, espn_id, logo_url, primary_color)",
    "join public.sports sp on sp.code = v.sport_code",
    "on conflict do nothing;",
    "",
  );

  out.push(
    "insert into public.fantasy_teams (season_id, name, slug)",
    "select se.id, v.name, v.slug",
    "from (values",
    values(league.teams.map((t) => [str(t.name), str(t.slug)])),
    ") as v(name, slug)",
    `join public.seasons se on se.name = ${str(s.name)}`,
    "on conflict do nothing;",
    "",
  );

  const pickRows = league.teams.flatMap((t) =>
    SPORT_CODES.map((code) => [str(t.slug), str(code), str(t.picks[code] ?? null)]),
  );
  out.push(
    "insert into public.picks (fantasy_team_id, sport_id, participant_id)",
    "select ft.id, sp.id, pa.id",
    "from (values",
    values(pickRows),
    ") as v(team_slug, sport_code, participant_name)",
    "join public.sports sp on sp.code = v.sport_code",
    `join public.seasons se on se.name = ${str(s.name)}`,
    "join public.fantasy_teams ft on ft.slug = v.team_slug and ft.season_id = se.id",
    "join public.participants pa on pa.sport_id = sp.id and pa.name = v.participant_name",
    "on conflict do nothing;",
    "",
  );
  return out.join("\n");
}

const league = leagueSchema.parse(JSON.parse(readFileSync(DATA_PATH, "utf8")));
assertRosterIsValid(league);
writeFileSync(OUT_PATH, build(league));
console.log(
  `wrote supabase/seed.sql (${league.teams.length} teams, ${league.teams.length * SPORT_CODES.length} picks)`,
);
